---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-1
  labels:
    app: deployment-1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-1
  template:
    metadata:
      labels:
        app: deployment-1
    spec:
      containers:
        - name: busybox
          image: busybox
          command: ['sh', '-c', 'i=0; file="/output/output.txt"; while true; do echo "$((i++)) | PID: $$ | File: $(readlink -f $file)" >> $file; sleep 5; done']
          volumeMounts:
            - name: volume-1
              mountPath: /output
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: volume-1
              mountPath: /input
      volumes:
        - name: volume-1
          persistentVolumeClaim:
            claimName: persistentvolumeclaim-1