---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistentvolume-1
  labels:
    app: persistentvolume-1
  namespace: default
spec:
  storageClassName: storageclass-1
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/node/persistentvolume-1"
  persistentVolumeReclaimPolicy: Delete