---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass-2
  labels:
    app: storageclass-2
  namespace: default
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.1.122
  share: /node/nfsserver-1
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nfsvers=4.1