---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: deployment-4
  name: deployment-4
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deployment-4
  template:
    metadata:
      labels:
        app: deployment-4
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
      initContainers:
        - name: busybox
          image: busybox:latest
          command: ['sh', '-c', 'until nslookup service-2.default.svc.cluster.local; do echo Waiting for service-2!; sleep 5; done;']
