{
 "title": "Netology",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "CPU utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{job=\"nodeexporter\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "CPU load average",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"nodeexporter\"}",
     "legendFormat": "CPU load average 1"
    },
    {
     "expr": "node_load5{job=\"nodeexporter\"}",
     "legendFormat": "CPU load average 5"
    },
    {
     "expr": "node_load15{job=\"nodeexporter\"}",
     "legendFormat": "CPU load average 15"
    }
   ]
  },
  {
   "title": "Memory free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Memory free" }
   ]
  },
  {
   "title": "Disk free",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{fstype!~\"tmpfs|fuse.lxcfs|squashfs|vfat\"}",
     "legendFormat": "Disk free"
    }
   ]
  }
 ]
}