# -*- mode: ruby -*-

ISO = "bento/ubuntu-20.04"
NET = "192.168.1."
DOMAIN = ".netology"
HOST_PREFIX = "ansible-control"

servers = [
  {
    :hostname => HOST_PREFIX + DOMAIN,
    :ip => NET + "110",
    :ssh_host => "20010",
    :ssh_vm => "22",
    :ram => 2048,
    :core => 2
  }
]

Vagrant.configure(2) do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: false
  servers.each do |machine|
    config.vm.define machine[:hostname] do |node|
      node.vm.box = ISO
      node.vm.hostname = machine[:hostname]
      node.vm.network "public_network", bridge: 'Intel(R) Ethernet Connection (2) I219-V', ip: machine[:ip]
      node.vm.provider "virtualbox" do |vb|
        vb.customize ["modifyvm", :id, "--memory", machine[:ram]]
        vb.customize ["modifyvm", :id, "--cpus", machine[:core]]
        vb.name = machine[:hostname]
      end
    end
  end
end
