---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: deployment-2
  labels:
    app: deployment-2
  namespace: default
spec:
  selector:
    matchLabels:
      app: deployment-2
  template:
    metadata:
      labels:
        app: deployment-2
    spec:
      containers:
        - name: multitool
          image: wbitt/network-multitool
          volumeMounts:
            - name: volume-2
              mountPath: /host/var/log/syslog
      volumes:
        - name: volume-2
          hostPath:
            path: /var/log/syslog