all:
  hosts:
    node1:
      ansible_host: 10.129.0.17
      ip: 10.129.0.17
      access_ip: 10.129.0.17
    node2:
      ansible_host: 10.129.0.24
      ip: 10.129.0.24
      access_ip: 10.129.0.24
    node3:
      ansible_host: 10.129.0.4
      ip: 10.129.0.4
      access_ip: 10.129.0.4
    node4:
      ansible_host: 10.129.0.27
      ip: 10.129.0.27
      access_ip: 10.129.0.27
    node5:
      ansible_host: 10.129.0.26
      ip: 10.129.0.26
      access_ip: 10.129.0.26
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
