---
apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  name: devuser-csr
spec:
  groups:
    - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1Z6Q0NBVDhDQVFBd0VqRVFNQTRHQTFVRUF3d0haR1YyZFhObGNqQ0NBU0l3RFFZSktvWklodmNOQVFFQgpCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFMQUVZL1JCbThxTC9pNUQvTnBFT3l0U2U5SDFJUVEzai9qTjZ0c0hMRDVMClJUTjlDOUpOYnpBR0FhbWpyaXhZQVNuVXp0cTdKUXhLTjF2NWV0RE1JRVJYQWhoSGdYUnhTWW1PSHJtZXY0ZGMKN1UwQXJLR1llTDh0OUlPQVJMcTlWaEhEenA1V1FWNHpYbUJ1REtzdWdHQ25mbTY3dks3N1ROTVYvcmZYOFpLVAo0TG43aDI3K2E1K2s0V2lxN2J6bGhRMXhwelZHRXhNNFdRWlNKOXZFcThFa1Vvckc5ZThBeFRYYk9rblM5VitXCnhVbFlSRy9FeHRkYzIrc1QzQzd3a2Zaam9rbWhscWFjRXZodWhpS29nb3k0MTRoOG05YTBKMTFGYmVWKy9rR3IKV0F0REwyb2hoRkVuNTg2bXFYbVVlb0lrR0Q1T09WQnJ1U1V4REdEblBxOENBd0VBQWFBQU1BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNEQ1paN2hBalhyUGFLS1VRb28yOUwwdGtkcXU0YnA4QnhZY0psUDVGM0FicTRObUpwCnF2b1EwdU00czJnTDFDR2x6dmYvQVFBY2dnVytKM1hra1NLT2FweCt5VkZkRkhweHErQkUvRU5aTHN4QXN0OU0KdXFvc1kwQ0lwUDdJTzViZjZkSThtanhlTGpQUzBvQzNaQ0l0RmpjNExXeHlmTktwZXFTaHpmdzhxbGJ2ZVg5awpSR1BzN0FTSFUzd1BsY2pKYWJlb0F6U0dKQmVPYm11SEJCb2ZKa2t4MU5TWUgra2pEcnovdUxmQUJUZGx2bmJ2Ci9HK2pvZk9oeG9PUzJPbzhLTEpPcmh2NEFlVG9QaFE1OWFNQmlGNTlHMGdKcXFjVm1tQ1UzMnlHaUp3SlhiYUwKdjFkWFp4L1F6aXZzMUZ1SVpoeUgxak5xLzhLMU5OeTk4RXUyCi0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  signerName: kubernetes.io/kube-apiserver-client
  usages:
    - digital signature
    - key encipherment
    - client auth
