---
clickhouse_group:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.46.36
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
vector_group:
  hosts:
    vector-01:
      ansible_host: 158.160.44.42
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
lighthouse_group:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.43.241
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
nginx_group:
  hosts:
    lighthouse-01:
      ansible_host: 158.160.43.241
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
added_hosts:
  hosts:
    clickhouse-01:
      ansible_host: 158.160.46.36
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    vector-01:
      ansible_host: 158.160.44.42
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
    lighthouse-01:
      ansible_host: 158.160.43.241
      ansible_user: yc-user
      ansible_ssh_common_args: -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no
